### ISSUE TITLE
Empty post request fails

### ISSUE THREAD

**Issue by baneizalfe** [googolmo/OkVolley#7]
When trying to send post request without any fields i get error
```
Caused by: java.lang.IllegalArgumentException: method POST must have a request body.
            at com.squareup.okhttp.Request$Builder.method(Request.java:236)
            at retrofit.client.OkClient.createRequest(OkClient.java:59)
            at retrofit.client.OkClient.execute(OkClient.java:53)
```
Thisi s known issue since okhttp 2.4 and was supposed to bi fixed in 2.5 (but isn't)

My fast and nasy workaround in OkKttpStack.java was
```
if (postBody == null) {
    builder.post(RequestBody.create(MediaType.parse(request.getBodyContentType()), ""));
} else {
    builder.post(RequestBody.create(MediaType.parse(request.getBodyContentType()), postBody));
}
```

**Comment by googolmo** [comment]
Ok I will try to workaround it.

**Comment by googolmo** [comment]
#8 fix it
